image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      cd no.hal.timers
      mvn install
      echo "run 'cd fxui; mvn -D"client.target=android" client:build client:package client:install to build apk"

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
